baseURL = "https://ss-o.github.io/"
title   = "Salvydas Lukosius"
languageCode = "en-gb"
theme = "hello"

PygmentsCodeFences = true
PygmentsStyle = "monokai"

paginate  = 10
rssLimit  = 10
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."

googleAnalytics = "G-QJP2ZTRCH9"

archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "docs"

buildDrafts  = true
buildFuture  = true
buildExpired = true
canonifyURLs = true

enableRobotsTXT = true
enableGitInfo   = true
enableEmoji     = true
enableMissingTranslationPlaceholders = true
disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false

[permalinks]
  posts = "/posts/:year/:month/:title/"

[author]
  name = "Salvydas Lukosius"

[blackfriday]
  hrefTargetBlank = true

[taxonomies]
  tag      = "tags"
  category = "categories"
  series   = "series"

[params]
  dateform        = "Jan 1, 2022"
  dateformShort   = "Jan 2"
  dateformNum     = "2022-01-02"
  dateformNumTime = "2022-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  description = "Personal Blog of Salvydas Lukosius"
  keywords = "Salvydas Lukosius, Digital Clouds, Blog"
  images = ["img"]

  homeSubtitle = "Digital Clouds Solution"

  # Prefix of link to the git commit detail page. GitInfo must be enabled.
  gitUrl = "https://github.com/ss-o/ss-o.github.io/commit/"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Sharing buttons
  # There are a lot of buttons preconfigured. If you want to change them,
  # generate the buttons here: https://sharingbuttons.io
  # and add them into your own `layouts/partials/sharing-buttons.html`
  enableSharingButtons = true

  # Integrate Javascript files or stylesheets by adding the url to the external assets or by
  # linking local files with their path relative to the static folder, e.g. "css/styles.css"
#  customCSS = []
#  customJS  = []

  # Toggle this option need to rebuild SCSS, requires extended version of Hugo
  justifyContent = true  # Set "text-align: justify" to .post-content.

  # Default theme "light" or "dark"
  defaultTheme = "dark"
  themeColor = "#252627"

  # Colors for favicons
  [params.favicon.color]
    mask = "#252627"
    msapplication = "#252627"
    theme = "#252627"

  [params.logo]
    logoText     = "$ cd ~/"
    logoHomeLink = "/"
    # Set true to remove the logo cursor entirely.
    # logoCursorDisabled = false
    # Set to a valid CSS color to change the cursor in the logo.
    logoCursorColor    = "#00FF00"
    # Set to a valid CSS time value to change the animation duration, "0s" to disable.
    logoCursorAnimate  = "3s"

  # Uncomment this if you want a portrait on your start page
  [params.portrait]
    path     = "img/ninja.png"
    alt      = "avatar"
    maxWidth = "260px"

  # Social icons
  [[params.social]]
#    name = "blog"
#    url  = "https://go.digitalclouds.dev"

  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/salldc/"

  [[params.social]]
    name = "email"
    url  = "mailto:sall@w-ss.io"

  [[params.social]]
    name = "github"
    url  = "https://github.com/ss-o/"

  [[params.social]]
    name = "gitlab"
    url  = "https://gitlab.com/ss-o/"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/ss-o/"

  [[params.social]]
    name = "stackoverflow"
    url  = "https://stackoverflow.com/users/13893752/salvydas-lukosius"

[languages]
  [languages.en]
    subtitle  = "Digital Clouds"
    weight    = 1
    copyright = 'Digital Clouds | Solutions'

#  [languages.lt]
#    subtitle  = "Hello Friend NG Theme"
#    weight    = 2
#    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

[menu]

#[[menu.main]]
#    identifier = "projects"
#    name = "Projects"
#    url = "projects/"
#    weight = 1

#[[menu.main]]
#    identifier = "posts"
#    name = "Posts"
#    url = "posts/"
#    weight = 2

#[[menu.main]]
#    name = "Categories"
#    url = "categories/"
#    weight = 3

#[[menu.main]]
#    name = "Tags"
#    url = "tags"
#    weight = 3

